#!/bin/bash
#
# chkconfig: 35 90 12
# description: This daemon monitors the reconn power button
#              and powers the box off when pressed.
#
# Get function from functions library
#. /etc/init.d/functions

# Start the service 
start() {
    ./PowerDaemon &
### Create the lock file ###
    touch /var/lock/subsys/PowerDaemon 
#success $"PowerDaemon server startup"
    echo
}
# Restart the service PowerDaemon
stop() {
       	killall PowerDaemon
	### Now, delete the lock file ###
       	rm -f /var/lock/subsys/PowerDaemon
       	echo
}
### main logic ###
	case "$1" in
	start)
		start
	;;
	stop)
		stop
	;;
	status)
		status PowerDaemon
	;;
	restart|reload|condrestart)
		stop
		start
	;;
	*)
		echo $"Usage: $0 {start|stop|restart|reload|status}"
		exit 1
	esac
exit 0
