//******************************************************************************
//******************************************************************************
//
// FILE:        version.c
//
// CLASSES:
//
// DESCRIPTION: Function used to return the reconn version to the caller.//
//******************************************************************************
//
//                       CONFIDENTIALITY NOTICE:
//
// THIS FILE CONTAINS MATERIAL THAT IS "HARRIS PROPRIETARY INFORMATION"  ANY 
// REVIEW, RELIANCE, DISTRIBUTION, DISCLOSURE, OR FORWARDING WITHOUT EXPRESSED 
// PERMISSION IS STRICTLY PROHIBITED.  PLEASE BE SURE TO PROPERLY DISPOSE ANY 
// HARDCOPIES OF THIS DOCUMENT.
//
//******************************************************************************
//
// Government Use Rights:
//
//           (Applicable only for source code delivered under U. S.
//           Government contracts)
//
//                           RESTRICTED RIGHTS LEGEND
//           Use, duplication, or disclosure is subject to restrictions
//           stated in the Government's contract with Harris Corporation,
//           RF Communications Division. The applicable contract number is
//           indicated on the media containing this software. As a minimum,
//           the Government has restricted rights in the software as
//           defined in DFARS 252.227-7013.
//
// Commercial Use Rights:
//
//           (Applicable only for source code procured under contracts other
//           than with the U. S. Government)
//
//                           TRADE SECRET
//           Contains proprietary information of Harris Corporation.
//
// Copyright:
//           Protected as an unpublished copyright work,
//                    (c) Harris Corporation
//           First fixed in 2004, all rights reserved.
//
//******************************************************************************
//
// HISTORY: Created <MM>/<DD>/<YYYY> by <USER>
// $Header:$
// $Revision: 1.3 $
// $Log:$
// 
//******************************************************************************
//******************************************************************************
//This file is auto generated when the reconn application is built. Do not edit this file// directly. Modify GenerateBuildVersion.pl instead.

#include <stdio.h>
#include <string.h>
#include "version.h"
static char gReconnVersionMajor[] = majorLevel;
static char gReconnVersionMinor[] = minorLevel;
static char gReconnVersionPatch[] = patchLevel;
static char gReconnSwVersionString[RECONN_STRING_MAX];
static char gReconnVersionBuildDate[] = "Mon Apr 30 07:45:24 2012";
static char gKernelVersionString[KERNEL_STRING_MAX];



char *getKernelSwVersion()
{
    FILE *filePtr;
    popen("uname -a > /temp/linuxVersion" , "w");
    filePtr = popen("/temp/linuxVersion", "r");
    fgets((char*)&gKernelVersionString, KERNEL_STRING_MAX, filePtr);
    return ((char*)&gKernelVersionString);
};



char *getReconnSwVersion()
{
    memset(&gReconnSwVersionString, 0, RECONN_STRING_MAX);
    strcat((char *)&gReconnSwVersionString, majorLevel);
    strcat((char *)&gReconnSwVersionString, ".");
    strcat((char *)&gReconnSwVersionString, minorLevel);
    strcat((char *)&gReconnSwVersionString, ".");
    strcat((char *)&gReconnSwVersionString, patchLevel);
    strcat((char *)&gReconnSwVersionString, " ");
    strcat((char *)&gReconnSwVersionString, gReconnVersionBuildDate);
    return ((char*)&gReconnSwVersionString);
};
